name: Build Thesis

on:
  push:
    branches:
      - main
    tags:
      - "**"
  pull_request:
  schedule:
    - cron: '0 16 * * 1'  # Build every monday, 16:00

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH

    - name: Install texlive
      run: |
        pip install https://github.com/maxnoe/texlive-batch-installation/archive/refs/tags/v0.3.1.tar.gz
        install_texlive -p $HOME/texlive -t 2023 --collections="-a" --package-file tex-packages.txt --update
        echo "$HOME/texlive/2023/bin/x86_64-linux" >> $GITHUB_PATH

    - name: Build document
      run: |
        latexmk
